#!/bin/bash
# Setup script for LLM Chat Node
# This script sets up the Gemini API key for the LLM chat functionality

echo "================================================"
echo "  Voice-Controlled Bot - LLM Chat Setup"
echo "================================================"
echo ""

# Check if API key is already set
if [ -n "$GEMINI_API_KEY" ]; then
    echo "✓ GEMINI_API_KEY is already set in your environment."
    echo ""
    echo "To use it with ROS2, make sure to source this in each terminal:"
    echo "  export GEMINI_API_KEY='your_api_key_here'"
else
    echo "GEMINI_API_KEY is not set."
    echo ""
    echo "To set it temporarily (current terminal only):"
    echo "  export GEMINI_API_KEY='your_api_key_here'"
    echo ""
    echo "To set it permanently, add the following line to your ~/.bashrc:"
    echo "  export GEMINI_API_KEY='your_api_key_here'"
    echo ""
    echo "Then reload your terminal with:"
    echo "  source ~/.bashrc"
fi

echo ""
echo "================================================"
echo "  How to Run the LLM Chat Node"
echo "================================================"
echo ""
echo "1. Set your Gemini API key (if not already done):"
echo "   export GEMINI_API_KEY='your_gemini_api_key'"
echo ""
echo "2. Source your ROS2 workspace:"
echo "   source ~/voice_ws/install/setup.bash"
echo ""
echo "3. Run the voice recognition node:"
echo "   ros2 run voice_cmd_bot voice_node"
echo ""
echo "4. In a separate terminal, run the command mapper (for robot movement):"
echo "   ros2 run voice_cmd_bot command_mapper"
echo ""
echo "5. In another terminal, run the LLM chat node (for conversations):"
echo "   ros2 run voice_cmd_bot llm_chat_node"
echo ""
echo "================================================"
echo "  Usage"
echo "================================================"
echo ""
echo "Movement commands (handled by command_mapper):"
echo "  - forward, backward, left, right, stop"
echo ""
echo "Conversational queries (handled by llm_chat_node):"
echo "  - Any other text will be sent to the Gemini LLM"
echo "  - Examples: 'What is the weather?', 'Tell me a joke', etc."
echo ""
echo "Both systems work in parallel without interfering!"
echo ""
